################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/AudioBV_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/DataLog_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/HWAdvanceFeatures.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionAR_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionCP_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionFX_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionGR_Manager.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/OTA.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/TargetPlatform.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/datalog_application.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/main.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/sensor_service.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/stm32l4xx_hal_msp.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/stm32l4xx_it.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_cdc_interface.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_conf.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_desc.c 

OBJS += \
./FS-SNS-ALLMEMS1/User/AudioBV_Manager.o \
./FS-SNS-ALLMEMS1/User/DataLog_Manager.o \
./FS-SNS-ALLMEMS1/User/HWAdvanceFeatures.o \
./FS-SNS-ALLMEMS1/User/MotionAR_Manager.o \
./FS-SNS-ALLMEMS1/User/MotionCP_Manager.o \
./FS-SNS-ALLMEMS1/User/MotionFX_Manager.o \
./FS-SNS-ALLMEMS1/User/MotionGR_Manager.o \
./FS-SNS-ALLMEMS1/User/OTA.o \
./FS-SNS-ALLMEMS1/User/TargetPlatform.o \
./FS-SNS-ALLMEMS1/User/datalog_application.o \
./FS-SNS-ALLMEMS1/User/main.o \
./FS-SNS-ALLMEMS1/User/sensor_service.o \
./FS-SNS-ALLMEMS1/User/stm32l4xx_hal_msp.o \
./FS-SNS-ALLMEMS1/User/stm32l4xx_it.o \
./FS-SNS-ALLMEMS1/User/usbd_cdc_interface.o \
./FS-SNS-ALLMEMS1/User/usbd_conf.o \
./FS-SNS-ALLMEMS1/User/usbd_desc.o 

C_DEPS += \
./FS-SNS-ALLMEMS1/User/AudioBV_Manager.d \
./FS-SNS-ALLMEMS1/User/DataLog_Manager.d \
./FS-SNS-ALLMEMS1/User/HWAdvanceFeatures.d \
./FS-SNS-ALLMEMS1/User/MotionAR_Manager.d \
./FS-SNS-ALLMEMS1/User/MotionCP_Manager.d \
./FS-SNS-ALLMEMS1/User/MotionFX_Manager.d \
./FS-SNS-ALLMEMS1/User/MotionGR_Manager.d \
./FS-SNS-ALLMEMS1/User/OTA.d \
./FS-SNS-ALLMEMS1/User/TargetPlatform.d \
./FS-SNS-ALLMEMS1/User/datalog_application.d \
./FS-SNS-ALLMEMS1/User/main.d \
./FS-SNS-ALLMEMS1/User/sensor_service.d \
./FS-SNS-ALLMEMS1/User/stm32l4xx_hal_msp.d \
./FS-SNS-ALLMEMS1/User/stm32l4xx_it.d \
./FS-SNS-ALLMEMS1/User/usbd_cdc_interface.d \
./FS-SNS-ALLMEMS1/User/usbd_conf.d \
./FS-SNS-ALLMEMS1/User/usbd_desc.d 


# Each subdirectory must supply rules for building sources it contributes
FS-SNS-ALLMEMS1/User/AudioBV_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/AudioBV_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/DataLog_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/DataLog_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/HWAdvanceFeatures.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/HWAdvanceFeatures.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/MotionAR_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionAR_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/MotionCP_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionCP_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/MotionFX_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionFX_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/MotionGR_Manager.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/MotionGR_Manager.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/OTA.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/OTA.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/TargetPlatform.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/TargetPlatform.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/datalog_application.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/datalog_application.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/main.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/main.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/sensor_service.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/sensor_service.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/stm32l4xx_hal_msp.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/stm32l4xx_hal_msp.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/stm32l4xx_it.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/stm32l4xx_it.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/usbd_cdc_interface.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_cdc_interface.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/usbd_conf.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_conf.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

FS-SNS-ALLMEMS1/User/usbd_desc.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Src/usbd_desc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


