################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_BlueNRG.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_accelero.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_audio_in.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_gg.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_gyro.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_humidity.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_magneto.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_pressure.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_sd.c \
/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_temperature.c 

OBJS += \
./Drivers/BSP/SensorTile/SensorTile.o \
./Drivers/BSP/SensorTile/SensorTile_BlueNRG.o \
./Drivers/BSP/SensorTile/SensorTile_accelero.o \
./Drivers/BSP/SensorTile/SensorTile_audio_in.o \
./Drivers/BSP/SensorTile/SensorTile_gg.o \
./Drivers/BSP/SensorTile/SensorTile_gyro.o \
./Drivers/BSP/SensorTile/SensorTile_humidity.o \
./Drivers/BSP/SensorTile/SensorTile_magneto.o \
./Drivers/BSP/SensorTile/SensorTile_pressure.o \
./Drivers/BSP/SensorTile/SensorTile_sd.o \
./Drivers/BSP/SensorTile/SensorTile_temperature.o 

C_DEPS += \
./Drivers/BSP/SensorTile/SensorTile.d \
./Drivers/BSP/SensorTile/SensorTile_BlueNRG.d \
./Drivers/BSP/SensorTile/SensorTile_accelero.d \
./Drivers/BSP/SensorTile/SensorTile_audio_in.d \
./Drivers/BSP/SensorTile/SensorTile_gg.d \
./Drivers/BSP/SensorTile/SensorTile_gyro.d \
./Drivers/BSP/SensorTile/SensorTile_humidity.d \
./Drivers/BSP/SensorTile/SensorTile_magneto.d \
./Drivers/BSP/SensorTile/SensorTile_pressure.d \
./Drivers/BSP/SensorTile/SensorTile_sd.d \
./Drivers/BSP/SensorTile/SensorTile_temperature.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/BSP/SensorTile/SensorTile.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_BlueNRG.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_BlueNRG.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_accelero.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_accelero.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_audio_in.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_audio_in.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_gg.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_gg.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_gyro.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_gyro.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_humidity.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_humidity.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_magneto.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_magneto.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_pressure.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_pressure.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_sd.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_sd.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/BSP/SensorTile/SensorTile_temperature.o: /home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile/SensorTile_temperature.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=hard -mfpu=fpv4-sp-d16 -std=c99 -DUSE_HAL_DRIVER '-DSTM32_SENSORTILE=1' -DSTM32L476xx -DUSE_STM32L4XX_NUCLEO -DALLMEMS1 -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Projects/Multi/Applications/ALLMEMS1/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Device/ST/STM32L4xx/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/STM32L4xx_HAL_Driver/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/SensorTile" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/CMSIS/Include" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/Common" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/SimpleBlueNRG_HCI/includes" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueNRG/Interface" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm6dsm" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/hts221" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lps22hb" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/lsm303agr" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Drivers/BSP/Components/stc3115" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionAR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionCP_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionFX_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MotionGR_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_BlueVoiceADPCM_Library/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_MetaDataManager" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Class/CDC/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/ST/STM32_USB_Device_Library/Core/Inc" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src" -I"/home/matteo/Scrivania/STM32CubeFunctionPack_ALLMEMS1_V3.4.0/Middlewares/Third_Party/FatFs/src/drivers"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


